name: pori-events
recipe: drupal8

compose:
  - compose.yml

config:
  webroot: web
  via: nginx
  php: '7.2'
  database: mariadb:10.1
  xdebug: false
  drush: 8.1.15

tooling:
  build.sh:
    service: appserver
    description: Execute build.sh
    cmd:
      - ./build.sh
  composer:
    service: appserver
    description: Run composer commands
    cmd:
      - php -dmemory_limit=-1 /usr/local/bin/composer

services:
  mailhog:
    type: mailhog
    hogfrom:
      - appserver

  appserver:
    build_as_root:
      - "apt-get update -y"
      - "apt-get install python-yaml -y"
    overrides:
      environment:
        WKV_SITE_ENV: lando
        DB_PASS_DRUPAL: drupal8
        DB_USER_DRUPAL: drupal8
        DB_HOST_DRUPAL: database
        DB_NAME_DRUPAL: drupal8

proxy:
  mailhog:
    - mail.lndo.site

events:
  # Clear caches after a database import
  post-db-import:
    - appserver: cd $LANDO_WEBROOT && drush cr -y
