<?php

/**
 * @file
 * Contains pori_pathauto.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\pathauto\PathautoPatternInterface;

/**
 * Implements hook_help().
 */
function pori_pathauto_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the pori_pathauto module.
    case 'help.page.pori_pathauto':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Pori events site pathauto alterations for event node type') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_pathauto_pattern_alter().
 */
function pori_pathauto_pathauto_pattern_alter(PathautoPatternInterface $pattern, array $context) {
  if ($context['module'] == 'node' && $context['op'] == 'update') {
    /* @var $node \Drupal\node\NodeInterface */
    $node = $context['data']['node'];

    // Events pathauto pattern depends on if hobby or not.
    // @todo: Take translations into account.
    if ($node->getType() == 'event') {
      $segment1 = ($node->hasField('field_hobby_is_hobby') && $node->field_hobby_is_hobby->value) ? 'harrastukset': 'tapahtumat';
      $pattern->setPattern($segment1 . '/' . $pattern->getPattern());
    }
  }
}
